AddToFavorites/AddToFavorites.MVC.UI/Models/CategoryListViewModel.cs
using AddToFavorites.Entities.Tangible;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AddToFavorites.MVC.UI.Models
{
    public class CategoryListViewModel
    {
      

        public List<Category> Categories { get; set; }
    }
}

AddToFavorites/AddToFavorites.MVC.UI/Models/LikeViewModel.cs
using AddToFavorites.Entities.Tangible;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AddToFavorites.MVC.UI.Models
{
    public class LikeViewModel
    {
        public Liked Liked { get; set; }
    }
}

AddToFavorites/AddToFavorites.MVC.UI/Models/ProductListViewModel.cs
using AddToFavorites.Entities.Tangible;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AddToFavorites.MVC.UI.Models
{
    public class ProductListViewModel
    {
        public List<Product> Products { get; set; }
    }
}

AddToFavorites/AddToFavorites.MVC.UI/Controllers/LikeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AddToFavorites.Business.Notional;
using AddToFavorites.MVC.UI.SessionServicies;
using Microsoft.AspNetCore.Mvc;

namespace AddToFavorites.MVC.UI.Controllers
{
    public class LikeController : Microsoft.AspNetCore.Mvc.Controller
    {
        private ILikeService _likeService;
        private ILikeSessionServicies _likeSessionServicies;
        private IProductService _productService;

        public LikeController(ILikeService likeService,
            ILikeSessionServicies likeSessionServicies,
            IProductService productService)
        {
            _likeService = likeService;
            _likeSessionServicies = likeSessionServicies;
            _productService = productService;
        }


        //ürünü favorilere ekleme işlemeni gerçekleştirmemiz gerek.
        public IActionResult AddToLiked(int productId)
        {
            var productToBeLiked = _productService.GetByFavoritesId(productId);
            var like = _likeSessionServicies.GetLike();
            _likeService.AddToFavorites(like, productToBeLiked);
            _likeSessionServicies.SetLike(like);
            return RedirectToAction("Index", "Product");
        }

        public ActionResult RemoveFromFavorites(int productId)
        {
            var like = _likeSessionServicies.GetLike();
            _likeService.RemoveFromFavorites(like, productId);
            _likeSessionServicies.SetLike(like);
            return RedirectToAction("Index", "Product");
        }
    }
}

AddToFavorites/AddToFavorites.MVC.UI/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AddToFavorites.Business.Notional;
using AddToFavorites.MVC.UI.Models;

namespace AddToFavorites.MVC.UI.Controller
{
    public class ProductController : Microsoft.AspNetCore.Mvc.Controller
    {
        private IProductService _productService;
        public ProductController(IProductService productService)
        {
            _productService = productService;
        }
        public IActionResult Index(int categorySelect = 0)
        {
            ProductListViewModel productModelList = new ProductListViewModel
            {
                Products = _productService.GetByCategory(categorySelect)
            };
            return View(productModelList);
        }

       
    }
}

AddToFavorites/AddToFavorites.MVC.UI/ViewComponents/CategoryListViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AddToFavorites.Business.Notional;
using AddToFavorites.DataAccess.Notional;
using AddToFavorites.MVC.UI.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace AddToFavorites.MVC.UI.ViewComponents
{
    public class CategoryListViewComponent:ViewComponent
    {
        private ICategoryService _categoryService;
        public CategoryListViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public ViewViewComponentResult Invoke()
        {
            var categoryListModel = new CategoryListViewModel
            {
                Categories = _categoryService.GetAll()
            };
            return View(categoryListModel);
        }
    }
}

AddToFavorites/AddToFavorites.MVC.UI/ViewComponents/LikeViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AddToFavorites.MVC.UI.Models;
using AddToFavorites.MVC.UI.SessionServicies;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ViewComponents;

namespace AddToFavorites.MVC.UI.ViewComponents
{
    public class LikeViewComponent : ViewComponent
    {
        private ILikeSessionServicies _likeSessionServicies;
        public LikeViewComponent(ILikeSessionServicies likeSessionServicies)
        {
            _likeSessionServicies = likeSessionServicies;
        }
        public ViewViewComponentResult Invoke()
        {
            var likeModel = new LikeViewModel
            {
                Liked = _likeSessionServicies.GetLike()
            };
            return View(likeModel);
        }
    }
}

AddToFavorites/AddToFavorites.MVC.UI/Views/Product/Index.cshtml
@model AddToFavorites.MVC.UI.Models.ProductListViewModel

@{
    Layout = "~/Views/_AnaSayfaLayout.cshtml";
}
<table class="table table-striped">
    <thead>
        <tr>
            <th>Ürünün Adı</th>
            <th>Fiyat </th>
            <th>Stok Durumu</th>
            <th>Favorilere Ekle</th>
        </tr>
        @foreach (var item in Model.Products)
        {
            <tr>
                <td>@item.ProductName</td>
                <td>@item.UnitPrice</td>
                <td>@item.UnitsInStock</td>
                <td><a asp-controller="Like" asp-action="AddToLiked" asp-route-ProductId="@item.ProductId"><i class="far fa-thumbs-up fa-2x text-danger"></i></a></td>
            </tr>
        }
    </thead>
</table>

AddToFavorites/AddToFavorites.MVC.UI/Views/Shared/Components/CategoryList/Default.cshtml
@model AddToFavorites.MVC.UI.Models.CategoryListViewModel


<ul class="list-group">
    @foreach (var categories in Model.Categories)
    {
        <li class="list-group-item"><a href="/Product/index?categorySelect=@categories.CategoryId" class="text-dark">@categories.CategoryName</a></li>

    }
</ul>

AddToFavorites/AddToFavorites.MVC.UI/Views/Shared/Components/Like/Default.cshtml
@model AddToFavorites.MVC.UI.Models.LikeViewModel

<div class="card">
    <div class="card-body">
        <ul class="list-group">
            @foreach (var item in Model.Liked.LikeMan)
            {

                <li class="list-group-item">
                    <div class="ProductName-Area py-2">
                        <span class="display-4 font-italic" style="font-family:'Bell MT'">Ürünün Adı</span>

                    </div>
                    <div class="ProductName-Value">
                        <span class="display-4" style="font-size:2.5rem;">@item.Product.ProductName</span>
                    </div>
                    <div class="Remove-Button mt-3">
                        <a class="btn btn-outline-secondary" asp-controller="Like" asp-action="RemoveFromFavorites" asp-route-ProductId="@item.Product.ProductId"><i class="fas fa-trash-alt px-1 text-danger"></i>Favori'den Çıkar</a>
                    </div>
                    <div class="DateTime-Area offset-8 text-center">
                        <strong style="letter-spacing: 2px;">Tarih</strong>
                        <hr class="border-dark" />
                        <small><i class="far fa-hourglass px-1 fa-2x"></i>@item.DateTime</small>
                    </div>

                </li>



                <hr class="border-danger" />
            }
        </ul>
    </div>
</div>

AddToFavorites/AddToFavorites.MVC.UI/Views/_AnaSayfaLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Favorilere Ekle</title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css">
    <link rel="stylesheet" href="~/Css/Stylee.css" />
</head>

<body>
    <section id="navbarMenu">
        <nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
            <div class="container">
                <button class="navbar-toggler" data-toggle="collapse" data-target="#vbrCollapse">
                    <span class="navbar-toggler-icon"></span>

                </button>
                <a href="#" class="navbar-brand text-white w-50">ASP.NET CORE MVC</a>
                <div class="collapse navbar-collapse" id="vbrCollapse">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active px-2"><a class="nav-link" href="#headerSection">Ana Sayfa</a></li>

                    </ul>
                </div>
            </div>
        </nav>
    </section>
    <section id="introduction" class="py-5">
        <div class="container-fluid py-5">
            <div class="row">
                <div class="col-md-6">
                    <div class="card">
                        <div class="card-body shadow">
                            <div class="categories">
                                <h4 class="display-4 text-center">
                                    <i class="fas fa-window-maximize px-3 text-warning"></i>Kategoriler
                                </h4>
                                <hr class="border-warning" />
                                @await Component.InvokeAsync("CategoryList")
                            </div>
                        </div>
                    </div>
                    <div class="product-favorites mt-3">
                        <h3 class="display-3 text-center"><i class="far fa-heart text-danger"></i>Favorilerim</h3>
                        <hr class="border-danger">
                        @await Component.InvokeAsync("Like")
                    </div>
                </div>


                <div class="col-md-6">
                    <h4 class="display-4 text-center">Ürünler<i class="fas fa-shopping-basket px-3 text-success"></i></h4>
                    <hr class="border-dark">
                    <div>
                        @RenderBody() <!--İndex.cshtml burası oluyor.-->
                    </div>
                </div>
            </div>
        </div>
    </section>



</body>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js">
</script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js">
</script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"></script>
<script src="script.js"></script>

</html>